#!/bin/bash
# Quick Start Commands for Railway Deployment

echo "=================================="
echo "🚀 RAILWAY DEPLOYMENT QUICK START"
echo "=================================="
echo ""
echo "Choose your deployment method:"
echo ""
echo "1️⃣  COMMIT AND PUSH TO GITHUB"
echo "   git add ."
echo "   git commit -m 'Add Railway deployment configuration'"
echo "   git push origin feature/about"
echo ""
echo "2️⃣  DEPLOY VIA RAILWAY DASHBOARD (Easiest)"
echo "   → Open: https://railway.app"
echo "   → Click: New Project → Deploy from GitHub repo"
echo "   → Select: Devcavi19/adal_ui"
echo "   → Branch: feature/about"
echo "   → Set environment variables (see below)"
echo ""
echo "3️⃣  OR DEPLOY VIA CLI (Advanced)"
echo "   npm install -g @railway/cli"
echo "   railway login"
echo "   railway init"
echo "   railway variables set SUPABASE_URL='your_value'"
echo "   railway variables set SUPABASE_KEY='your_value'"
echo "   railway variables set SUPABASE_SERVICE_KEY='your_value'"
echo "   railway variables set GOOGLE_API_KEY='your_value'"
echo "   railway variables set SECRET_KEY='e54266e0192db56294e0dceb0d3d10797e4049dfd7b4fbafcaa64f416181255d'"
echo "   railway variables set FLASK_ENV='production'"
echo "   railway variables set DEBUG='False'"
echo "   railway up"
echo ""
echo "=================================="
echo "🔐 ENVIRONMENT VARIABLES TO SET:"
echo "=================================="
echo ""
echo "SUPABASE_URL          = [Get from Supabase Dashboard]"
echo "SUPABASE_KEY          = [Anon key from Supabase]"
echo "SUPABASE_SERVICE_KEY  = [Service role key from Supabase]"
echo "GOOGLE_API_KEY        = [From Google AI Studio]"
echo "SECRET_KEY            = e54266e0192db56294e0dceb0d3d10797e4049dfd7b4fbafcaa64f416181255d"
echo "FLASK_ENV             = production"
echo "DEBUG                 = False"
echo ""
echo "=================================="
echo "📚 DOCUMENTATION:"
echo "=================================="
echo ""
echo "→ DEPLOYMENT_VISUAL_GUIDE.md  (START HERE!)"
echo "→ QUICK_REFERENCE.md          (For presentation)"
echo "→ FINAL_CHECKLIST.txt         (Complete checklist)"
echo "→ DEPLOYMENT.md               (Detailed guide)"
echo ""
echo "=================================="
echo "✅ ALL FILES READY FOR DEPLOYMENT"
echo "=================================="
